# .github/workflows/deploy.yml
name: Deploy

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy para o ambiente
        run: |
          if [[ "${GITHUB_REF##*/}" == "main" ]]; then
            echo "Deploy de produção"
            ssh -o StrictHostKeyChecking=no univates@177.44.248.68 "sudo su -c 'cd /home/univates/prod/ && chmod +x ./deploy.sh && ./deploy.sh'"
          else
            echo "Deploy de homologação"
            ssh -o StrictHostKeyChecking=no univates@177.44.248.68 "sudo su -c 'cd /home/univates/homolog/ && chmod +x ./deploy.sh && ./deploy.sh'"
          fi